[package]
name = "soundcharts-cli"
version = "0.0.0"
edition = "2021"
description = "CLI for the Soundcharts API"
repository = "https://github.com/oneortwo/soundcharts-cli"
license = "MIT"

[[bin]]
name = "sc"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
clap_complete = "4"
reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.8"
dialoguer = "0.11"
console = "0.15"
comfy-table = "7"
dirs = "6"
urlencoding = "2"
